openapi: "3.0.0"
info:
  version: 1.0.0
  title: Listings API
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /listings:
    get:
      summary: Listings By Type
      operationId: listListings
      tags:
        - Listings
      parameters:
        - name: Type
          in: query
          description: filter by Type
          required: false
          schema:
            type: string
          allowReserved: true
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new Listing
      operationId: createListing
      tags:
        - Listings
      requestBody:
        description: the listing to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Listing"
      responses:
        default:
          description: unexpected error
  /listings/{:id}:
    get:
      summary: Get By Id
      operationId: listById
      tags:
        - Listings
      parameters:
        - name: :id
          in: path
          description: listing id
          required: true
          schema:
            type: string
            format: int64
          allowReserved: true
      responses:
        "200":
          description: List Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Replace an listing by ID
      operationId: putListing
      tags:
        - Listings
      parameters:
        - name: id
          in: path
          description: listing id
          required: true
          schema:
            type: string
            format: int64
      requestBody:
        description: the listing you replaced
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Listing"
      responses:
        "200":
          description: The replaced listing was created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListing"
        "201":
          description: The replaced listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListing"
        "204":
          description: Nothing happened
  /listings/{id}:
    delete:
      summary: Delete a listing by id
      operationId: delete one Listing
      tags:
        - Listings
      parameters:
        - name: id
          in: path
          description: listing Id
          required: true
          schema:
            type: string
            format: int64
      responses:
        default:
          description: no user with this id
components:
  schemas:
    Listing:
      type: object
      properties:
        Address:
          type: string
        Location:
          type: string
        Price:
          type: number
        MonthlyFee:
          type: string
        Type:
          type: string
        Coordinate:
          type: object
          properties:
            Longitude:
              type: number
            Latitude:
              type: number
    ResponseListing:
      allOf:
        - $ref: "#/components/schemas/Listing"
        - properties:
            id:
              type: integer
            _id:
              type: string
              format: uuid
    ResponseListings:
      type: array
      items:
        $ref: "#/components/schemas/ResponseListing"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
